name: ericdacus
favicon: null
layout_spectrum: 0.028832189505919814
typography_spectrum: 0.9643591793719679
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6755127646028996
  lightness: 0.8008363950066268
  saturation: 0.7006007602903992
  rhythmicContrast: 0.1416535738389939
purpose: []
